# GitHub Dependabot configuration file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.apache.felix:maven-bundle-plugin"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "biz.aQute.bnd:biz.aQute.bndlib"
        versions:
          - ">=7.0.0" # does not support java 8
      - dependency-name: "biz.aQute.bnd:bnd-maven-plugin"
        versions:
          - ">=7.0.0" # does not support java 8
      - dependency-name: "org.apache.derby:derby"
        versions:
          - ">=10.15.0" # does not support java 8
      - dependency-name: "org.springframework:spring-*"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-*"
        versions:
          - ">=6.0.0" # does not support java 8
      - dependency-name: "org.apache.openjpa:openjpa"
        versions:
          - ">=4.0.0" # does not support java 8
      - dependency-name: "org.mockito:mockito*"
        versions:
          - ">=5.0.0" # does not support java 8
      - dependency-name: "org.eclipse:osgi" # should be upgraded to org.eclipse.platform:org.eclipse.osgi
        versions:
          - ">=3.9.1" # higher version removed CompositeBundle used by some artifacts

